/**
 * wl_songs_scraper/config.ts
 *
 * Everything you might reasonably want to change lives here.
 * Nothing else in this folder hard-codes a path, an id, or a name.
 */

/** Root of the worship-leader archive. Each leader has a folder directly under this. */
export const LEADERS_ROOT =
  'C:\\Users\\serve\\OneDrive\\MEDIA SHARE\\WORSHIP TEAM SONG DATABASE\\Worship Leaders Line-up'

/**
 * Service types whose plans get filed into the leader archive.
 *
 * The account has eight. "Turn into Praise!" is the Sunday morning service —
 * one plan per Sunday covering all three service times — and is the only one
 * the archive is about. WORSHIP NIGHT (972330) is a separate monthly evening
 * and is deliberately excluded; add it here if those should be filed too.
 *
 * Empty array = every service type.
 */
export const SERVICE_TYPE_IDS: string[] = ['957307'] // Turn into Praise!

/**
 * Folders under LEADERS_ROOT that are NOT people. Excluded from name matching
 * so they can never be proposed as a match for a scheduled leader.
 */
export const NON_PERSON_FOLDERS = ['DIVERSED CONTEMPORARY SONGS', 'OLD WORSHIP LEADERS']

/**
 * The team position that identifies the worship leader on a plan.
 *
 * Matched against `team_position_name` on the plan's team members, ignoring
 * case and punctuation. Note this is NOT looked up via /team_positions — that
 * endpoint returns nothing matching on this account.
 */
export const WORSHIP_LEADER_POSITION = 'Worship Leader'

/** How far back to look when sampling who has led. Probe only. */
export const PROBE_MONTHS_BACK = 24

/** Generated by the probe, edited by you. Overrides always win over auto-matching. */
export const MAPPING_FILE = 'wl_songs_scraper/mapping.json'

/** Where the probe writes its findings. */
export const PROBE_REPORT = 'wl_songs_scraper/probe-report.json'

/** Appended to a file being written; renamed into place only once complete. */
export const PARTIAL_SUFFIX = '.part'
